#!/bin/bash
# Author   : Samiux (https://www.infosec-ninjas.com)
# Date     : JUL 20, 2017
# License  : GPLv3 (Open Source)

echo "Setting TimeZone..."
TZ=$(wget -qO - http://geoip.ubuntu.com/lookup | sed -n -e 's/.*<TimeZone>\(.*\)<\/TimeZone>.*/\1/p')
sudo timedatectl set-timezone $TZ
TZ=$(timedatectl status | grep "Time zone:" | awk '{print $3}')
echo "TimeZone set to $TZ"
