#!/bin/bash
# Author   : Samiux (https://samiux.github.io)
# Date     : MAR 12, 2020
# License  : GPLv3 (Open Source)

if [ -d /var/tmp/netdata ]
then
        cd /var/tmp/netdata

        # to avoid "error: cannot open .git/FETCH_HEAD: Permission denied"
        sudo chmod a+rw .git/FETCH_HEAD

        sudo git pull | grep "Already up to date." &> /dev/null
        if [ $? == 0 ]
        then
                echo "Already up to date!"
        else
                echo "Compiling netdata ..."
                sudo ./netdata-installer.sh --dont-wait --enable-ebpf

                #sudo systemctl restart netdata
        fi
else
        cd /var/tmp
        sudo git clone https://github.com/firehol/netdata.git
        cd netdata

        sudo ./netdata-installer.sh --dont-wait --enable-ebpf

        #sudo systemctl restart netdata
fi

